deploy:
  provider: npm
  language: node_js
node_js:
- 4.2.2
script:
- npm run main
  email: sandbox_JSUI@coveo.com
  api_key:
    secure: bq9rlPfjtK9OvXZUu4iny3RhJidRlke2Fm1xmeKKWIevJeRWqXT6uf1aEZvCbc5G26pkUDgonUo5yXpURjWjyXDVmP++g4BE3VomRBhykBRSUWN/UCRblNsa0Um4NjQxl+U20vPrs50gYt5KazmJIvF8ELA1LhqCEio6YvWawDGres9gY8FXGIvKLCPY0VyFHEJLZGWOz0kOT7WC1AuAZ9NCh5dy/5lt81eNfiyHDfFO6Mhy9J22HhzVVwwnFdBelBMUtsTjA16xF3FpUXCsxAT0XSl3DAcsSmiTrLj/HKryPWLXZ3sAmM3QlLgPas97sQxgdLplAVsejvg07xv7TmI+JNTz6T+ng0H1DU6YcHMAc1iNbDOycesHvJre8MkMJDJ900rRfMy8tt7ow59bIqkTM7FkHgg/G4yqekF/9aDjIzoqBhexgIR2MJjVsdG0j9D+vQZVV6DbHalz3WYz6uwjVeoBei9jxasw7tInRYJLU9me+j1LKxKFf4JADLpZZB2o0Cp/oW/5ZoH0khbVcEHd9Ka6zgbCVeD/Ut0epaqKN9T909Cz8VHIGQdHznKwTCquvCe41CVarGRy1gGZ/TwF09WgELr1KWWAbaUsI+smdOHIQRg/ObWQQjoIwdnKD43ToM//KKoyaxorY52k85JE/nObYG5zICpCGRi5Q60=
  on:
    tags: true
    repo: coveord/search-ui-version
